//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace frontend.UserService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UserService.IUserService")]
    public interface IUserService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/Signup", ReplyAction="http://tempuri.org/IUserService/SignupResponse")]
        bool Signup(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/Signup", ReplyAction="http://tempuri.org/IUserService/SignupResponse")]
        System.Threading.Tasks.Task<bool> SignupAsync(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/Signin", ReplyAction="http://tempuri.org/IUserService/SigninResponse")]
        bool Signin(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/Signin", ReplyAction="http://tempuri.org/IUserService/SigninResponse")]
        System.Threading.Tasks.Task<bool> SigninAsync(string email, string password);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUserServiceChannel : frontend.UserService.IUserService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserServiceClient : System.ServiceModel.ClientBase<frontend.UserService.IUserService>, frontend.UserService.IUserService {
        
        public UserServiceClient() {
        }
        
        public UserServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Signup(string email, string password) {
            return base.Channel.Signup(email, password);
        }
        
        public System.Threading.Tasks.Task<bool> SignupAsync(string email, string password) {
            return base.Channel.SignupAsync(email, password);
        }
        
        public bool Signin(string email, string password) {
            return base.Channel.Signin(email, password);
        }
        
        public System.Threading.Tasks.Task<bool> SigninAsync(string email, string password) {
            return base.Channel.SigninAsync(email, password);
        }
    }
}
